import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const beVietnamPro = Be_Vietnam_Pro({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700", "800", "900"],
	variable: "--font-be-vietnam-pro",
	display: "swap",
});

const lacoFont = localFont({
	src: "../fonts/La-Co-1.0-Demo.ttf",
	variable: "--font-laco",
	display: "swap",
});

export const metadata: Metadata = {
	title: "1939 - 1945 🇻🇳",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${beVietnamPro.variable} ${lacoFont.variable} antialiased font-sans`}>
				{children}
			</body>
		</html>
	);
}
